### PR TITLE
Prevent donna from crashing when seeing a require with generated path

### PR DESCRIPTION
**Pull request by lee-dohm**
Fixes lee-dohm/endokken#20

This doesn't generate any metadata for the require, but at least it doesn't crash :grinning:

### CODE REVIEW

**Comment by lee-dohm** [comment]
@benogle @kevinsawicki Thoughts?

**Comment by benogle** [comment]
I hate the `constructDelta` method. It's something we inherited from the original implementation on biscotto. Can you put this inline and just check for the JSON bits you need, rather than the whole JSON blob? There are a couple other specs in there that are inline for reference.

**Comment by lee-dohm** [comment]
Absolutely. I'll take care of it.

**Comment by lee-dohm** [comment]
@benogle Also, should this be accessible to the non-github-maintainers team of the Atom org?

**Comment by kevinsawicki** [comment]
> Also, should this repository be accessible to the non-github-maintainers team of the Atom org?

The answer to this question is always yes, the usual reason the team doesn't is because we have to manually add new repos to the team after the repo gets created and sometimes we forget.

**Comment by benogle** [comment]
I've added this repo to your team. Let me know if you see any other repos that arent in it.

**Comment by lee-dohm** [comment]
Ok, I figured it was something like that :grinning: I'll let you know.

**Comment by kevinsawicki** [comment]
@lee-dohm do all the tests pass for you locally? I'm seeing some failures on master

**Comment by lee-dohm** [comment]
No, they don't. I used fit to just focus on my new test. I can go through and fix them after I get home from work if it would be helpful?

**Comment by kevinsawicki** [comment]
> I can go through and fix them after I get home from work if it would be helpful?

Yeah, perhaps @benogle knows the status of them before you get going.

**Comment by benogle** [comment]
Master passes for me

**Comment by kevinsawicki** [comment]
@benogle looks like master fails on Travis, https://travis-ci.org/atom/donna/builds/50665626 I wonder what is up.

**Comment by lee-dohm** [comment]
I get the same output as Travis. I'll dig in to this and submit a separate PR.

**Comment by kevinsawicki** [comment]
Thanks for fixing this :sun_with_face: published as `1.0.11`

**Pull request merged**
